global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sgau-gateway-service.onrender.com"]

  - job_name: auth
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sgau-auth-service.onrender.com"]

  - job_name: student
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sgau-student-service.onrender.com"]

  - job_name: academic
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sgau-academic-service.onrender.com"]

  - job_name: enrollment
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sgau-enrollment-service.onrender.com"]

  - job_name: grades
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sgau-grades-service.onrender.com"]

  - job_name: payment
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sgau-payment-service.onrender.com"]

  - job_name: reporting
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["sgau-reporting-service.onrender.com"]